on:
  pull_request:

name: Continuous integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.98.0
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  checks:
    name: ${{ matrix.task.name }}
    needs: fmt
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - name: Clippy
            components: clippy
            cache-all-targets: true
            run: cargo clippy --workspace --all-targets --keep-going --locked -- -D warnings
          - name: Test
            components: ""
            cache-all-targets: false
            run: cargo test --workspace --locked
          - name: Coverage
            components: llvm-tools-preview
            cache-all-targets: true
            run: cargo llvm-cov --workspace --locked --summary-only
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: dtolnay/rust-toolchain@1.98.0
        with:
          components: ${{ matrix.task.components }}
      - if: matrix.task.name == 'Coverage'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-targets: ${{ matrix.task.cache-all-targets }}
      - run: ${{ matrix.task.run }}
